#!/bin/bash

 # Exit on first failing command.
 set -e
 # Echo commands to console.
 set -x

docker version
docker-compose version

docker-compose up -d

docker exec ketohub npm install
docker exec ketohub ./build