FROM docker.io/node:8-stretch

# Install and build the application
COPY . /app
WORKDIR /app
RUN npm install \
    && cd functions && npm install && cd ../ \
    && ./node_modules/@angular/cli/bin/ng build --prod --aot \
    && ./node_modules/scssfmt/cli.js  --recursive 'src/**/**/*.scss' --diff \

# Expose ports
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
