#!/bin/bash

 # Exit on first failing command.
 set -e
 # Echo commands to console.
 set -x

IMAGE_VERSION=$(git rev-parse HEAD)
IMAGE_NAME="ketohub:${IMAGE_VERSION}"
CONTAINER_NAME="ketohub-container"

docker version

docker build \
  --tag "$IMAGE_NAME" \
  .

docker run \
  --tty \
  --detach \
  --volume "${PWD}:/app" \
  --name "$CONTAINER_NAME" \
  "$IMAGE_NAME"

docker exec "$CONTAINER_NAME" npm install
docker exec "$CONTAINER_NAME" bash ./build